version: "3.4"

services:
  boilerplate:
    build:
      target: base
    volumes:
      - ./src:/base/src
      - ./public:/base/public
      - ./tailwind.config.js:/base/tailwind.config.js
    command: yarn dev
    ports:
      - "3000:3000"
